from: '"loading.io Support" <contact@loading.io>'
subject: Email Verification from loading.io
content: |
  You receive this mail because there is an email verification request for the account using this email in loading.io. If you didn't sign up loading.io, please just ignore this mail, or reply directly to ask removing email.

  To verify your email, click following link:

  [https://loading.io/me/mail/verify/#{token}](https://loading.io/me/mail/verify/#{token})

  Thanks,
  loading.io team
