from: '"loading.io Support" <noreply@loading.io>'
subject: Password Reset from loading.io
content: |
  You receive this mail because there is a password reset request for the account using this email in loading.io. If you didn't ask for password reset, please just ignore this mail.

  To reset your password, click following link:

  [https://loading.io/me/passwd/reset/#{token}](https://loading.io/me/passwd/reset/#{token})

  Thanks,
  loading.io team
